### ISSUE TITLE
Side bar not working

### ISSUE THREAD

**Issue by kmaustral** [devonthesofa/obsidian-note-status#6]
This looks like a promising plugin. It is most welcome.

When I try to open the sidebar, it takes a long time. I thought my vault had crashed. Is it possible not to include unassigned notes?

![Image](https://github.com/user-attachments/assets/4c66acdb-2c3a-4a8a-a11f-fa4c4f4403a2)

Also, as you see, I am not getting the note title in the sidebar. 

In fact, this plugin removes all the note titles in the File sidebar as well. 

I don't see any warnings in the console.

**Comment by soler1212** [comment]
Thank you @kmaustral for trying out the Note Status plugin and for reporting these issues! I've identified two problems based on your feedback:

**Issue 1: Slow loading of the status pane**

The plugin currently loads all notes, including those without any assigned status (marked as "unknown"). For large vaults, this creates significant performance issues. I'll implement a new setting that allows hiding notes with "unknown" status in the status pane, which should dramatically improve loading times(I will try to also optimize it for large vaults).

**Issue 2: Missing note titles in sidebars**

I've found a bug in the code that handles status icon rendering which is accidentally removing title elements in both the plugin's status pane and the main file explorer. This happens because the icon cleanup routine is using overly broad selectors that can affect title elements.

**Both issues will be fixed in the next update with:**

- A new setting called "Hide notes with unknown status in status pane" that you can toggle on for better performance
- More specific DOM element targeting to prevent the removal of title elements

The update should be ready as soon as I can make time for it. I don't have much free time currently, but I want to prioritize these fixes since they affect core functionality. 
_**Thank you for your patience and for helping improve the plugin!!!**_

**Comment by soler1212** [comment]
@kmaustral  Great news! I've just released v1.0.12 which addresses both issues you reported:
**Fixed Issues:**

- Performance: Added "Exclude unassigned notes from status pane" option in settings - dramatically improves loading times
- Missing Titles: Fixed the DOM manipulation bug that was removing note titles from both sidebars

**Additional Improvements:**

- Added pagination (100 notes per page) for better navigation
- Non-blocking rendering prevents UI freezing
- Optimized for large vaults (tested with 15,000+ notes)

**To use:**

- Update the plugin to v1.0.12
- Go to Settings → Note Status
- Enable "Exclude unassigned notes from status pane"

The status pane should now load instantly and all your note titles should be visible again.

_Note: I haven't had extensive time for testing, so if you encounter any issues I've missed, please let me know and I'll fix them promptly. Thanks for your patience and for helping identify these critical issues!_

**Comment by kmaustral** [comment]
I'm afraid that the issue persists in the updated version:
![Image](https://github.com/user-attachments/assets/72cc2ba2-1fad-4110-9aef-235d9d7c27e7)

**Comment by kmaustral** [comment]
I've solved it. It was a setting in the Anappucin theme. Is should be aligned Right, not Left. 

![Image](https://github.com/user-attachments/assets/6750325c-38dc-4cc9-848f-4a9506bbb838)
